version: "3.1"
services:

    composer_installation:
      container_name: composer
      image: composer
      working_dir: /application
      volumes:
        - ./:/application
      command: composer install --ignore-platform-reqs
    
    webserver:
      image: nginx:alpine
      container_name: website-webserver
      networks:
      - webapp
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8082:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: website-php-fpm
      working_dir: /application
      networks:
      - webapp
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini


    db:
      image: mysql:5.7
      container_name: mysql
      ports:
      - "3306:3306"
      volumes:
      - dbdata:/var/lib/mysql
      networks:
      - webapp
      restart: always
      environment:
        MYSQL_DATABASE: docker_example
        MYSQL_ROOT_PASSWORD: docker_example_password
        MYSQL_USER: docker_example_user
        MYSQL_PASSWORD: docker_example_password
        
      



    phpmyadmin:
      container_name: phpmyadmin
      depends_on:
        - db
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
        - '8080:80'
      environment:
        PMA_HOST: db
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: docker_example_password
      networks:
      - webapp
      links:
      - db
 
    app: 
      container_name: app
      networks:
      - webapp
      build: 
        context: .
        dockerfile: app.Dockerfile
        
    

volumes:
  dbdata:
    driver: local

    
networks:
  webapp:
    driver: bridge